config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user

  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.new
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = Book.all
    @book = @user.books.all

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@book.errors.count, "error") %> errors prohibited this obj form begin saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with model: @book,local:true do |f| %>

  <div class="form-group">
    <lable for="book_title">Title</lable>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <lable for="book_opinion">Opinion</lable>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
  <%= link_to "Show", @book %>
  |

  <%= link_to "Back", '/books' %>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="col-md-3">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj form begin saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to "", edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book, url:'/books', local:true do |f| %>

  <div class="form-group">
    <lable for="book_title">Title</lable>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <lable for="book_opinion">Opinion</lable>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>

        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>

        <td><%= book.body %></td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to "", edit_user_path(@book.user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book_new, local:true do |f| %>

  <div class="form-group">
    <lable for="book_title">Title</lable>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <lable for="book_opinion">Opinion</lable>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
            <%= @user.name %>
          <% end %>
        </td>

        <td>
          <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
          <% end %>
        </td>

        <td><%= @book.body %></td>
        <td>
          <% if @user.id == current_user.id %>
            <%= link_to "Edit", edit_book_path, class: "btn btn-sm btn-success" %>
          <% end %>
        </td>

        <td>
          <% if @user.id == current_user.id %>
            <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか?" }, class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/homes/about.html.erb
<h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"><strong>Bookers</strong>!</i></h1>

app/views/homes/top.html.erb
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
  <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>

  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
    </div>

    <div class="row">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li>
                  <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " Users", '/users', class: "fas fa-users nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " Books", '/books', class: "fas fa-book-open nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>

                <li>
                  <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <div class="container">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  <% if @user.errors.any? %>
        <div id="error_explanation">
            <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj form begin saved:</h3>
            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
  <%= form_with model: @user, local:true do |f| %>
  <div class="form-group">
    <lable for="user_name">Name</lable>
    <%= f.text_field :name, class: "form-control name" %>
  </div>

  <div class="form-group">
    <lable for="user_image">Image</lable>
    <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
  </div>

  <div class="form-group">
    <lable for="user_introduction">Introduction</lable>
    <%= f.text_area :introduction, class: "form-control inttroduction" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update User", class: "btn btn-secondary" %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to "", edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book, local:true do |f| %>

  <div class="form-group">
    <lable for="book_title">Title</lable>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <lable for="book_opinion">Opinion</lable>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: @book_new, local:true do |f| %>

  <div class="form-group">
    <lable for="book_title">Title</lable>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>

  <div class="form-group">
    <lable for="book_opinion">Opinion</lable>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @book.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>

        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>

        <td><%= book.body %></td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>